

-- EXAMEN ADMISION: UNMSM
-- ========================>

USE PROYECTOS

/*

Se importa la base CSV a SQL Server y se realizaran diversas consultas de importancia.

*/




-- ESCUELAS - FACULTADES 
-- =======================:


IF OBJECT_ID('Tempdb..#data_admision','U') IS NOT NULL DROP TABLE #data_admision
SELECT * INTO #data_admision
FROM data_admision_20242
UNION
SELECT *
FROM data_admision_20251
UNION
SELECT *
FROM data_admision_20252
-- WHERE CODIGO_ESCUELA = 225


-- ASIGNACION DE FACULTAD Y AREA ACADEMICA. 
-- ========================================:

/*
SELECT DISTINCT OBS
FROM #data_admision
*/

IF OBJECT_ID('Tempdb..#data_admision_facultades','U') IS NOT NULL DROP TABLE #data_admision_facultades
; WITH Escuelas AS (

		SELECT *
			, CASE WHEN ESCUELA_PROFESIONAL = 'NUTRICION - LIMA' THEN 'NUTRICION'
				   WHEN ESCUELA_PROFESIONAL IN ('DERECHO - LIMA') THEN 'DERECHO' -- 'DERECHO - VILLA RICA'
				   WHEN ESCUELA_PROFESIONAL = 'EDUCACIÓN FÍSICA - LIMA' THEN 'EDUCACIÓN FÍSICA'
				   WHEN ESCUELA_PROFESIONAL = 'INGENIERÍA AGROINDUSTRIAL - LIMA' THEN 'INGENIERÍA AGROINDUSTRIAL'
				   WHEN ESCUELA_PROFESIONAL = 'CIENCIAS BIOLÓGICAS - LIMA' THEN 'CIENCIAS BIOLÓGICAS'
				   WHEN ESCUELA_PROFESIONAL = 'ADMINISTRACIÓN - LIMA' THEN 'ADMINISTRACIÓN'
				   WHEN ESCUELA_PROFESIONAL = 'ADMINISTRACIÓN DE TURISMO - LIMA' THEN 'ADMINISTRACIÓN DE TURISMO'
				   WHEN ESCUELA_PROFESIONAL = 'ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES - LIMA' THEN 'ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES'
				   WHEN ESCUELA_PROFESIONAL = 'CONTABILIDAD - LIMA' THEN 'CONTABILIDAD'  
				   WHEN ESCUELA_PROFESIONAL = 'GESTIÓN TRIBUTARIA - LIMA' THEN 'GESTIÓN TRIBUTARIA'  
				   WHEN ESCUELA_PROFESIONAL = 'AUDITORÍA EMPRESARIAL Y DEL SECTOR PÚBLICO - LIMA' THEN 'AUDITORÍA EMPRESARIAL Y DEL SECTOR PÚBLICO'
				   WHEN ESCUELA_PROFESIONAL = 'PRESUPUESTO Y FINANZAS PÚBLICAS - LIMA' THEN 'PRESUPUESTO Y FINANZAS PÚBLICAS' 
				   WHEN ESCUELA_PROFESIONAL = 'CIENCIAS DE LA COMPUTACIÓN' THEN 'CIENCIA DE LA COMPUTACIÓN'  
				   WHEN ESCUELA_PROFESIONAL = 'INGENIERÍA DE MINAS - LIMA' THEN 'INGENIERÍA DE MINAS'
				   WHEN ESCUELA_PROFESIONAL = 'INGENIERÍA ELÉCTRICA - LIMA' THEN 'INGENIERÍA ELÉCTRICA'
				   WHEN ESCUELA_PROFESIONAL = 'INGENIERÍA GEOLÓGICA - LIMA' THEN 'INGENIERÍA GEOLÓGICA'
				   WHEN ESCUELA_PROFESIONAL = 'NUTRICION - LIMA' THEN 'NUTRICION'
				   WHEN ESCUELA_PROFESIONAL = 'PSICOLOGÍA - LIMA' THEN 'PSICOLOGÍA'
				   ELSE ESCUELA_PROFESIONAL
				   END AS ESCUELA_PROFESIONAL_OFICIAL
			, CASE WHEN OBS IN ('ALCANZO VACANTE SEGUNDA OPCIÓN', 'ALCANZO VACANTE PRIMERA OPCIÓN', 'ALCANZO VACANTE') THEN 'ALCANZO VACANTE' 
				   ELSE NULL END OBS_OFICIAL
		FROM #data_admision
	

), Facultades AS (

	SELECT *
	, CASE -- CIENCIAS DE LA SALUD
		   WHEN CODIGO_ESCUELA IN (11, 12, 13, 141, 142, 143, 144, 15) AND ESCUELA_PROFESIONAL NOT IN ('MATEMÁTICA', 'ESTADÍSTICA', 'INVESTIGACIÓN OPERATIVA')  THEN 'FACULTAD MEDICINA'
		   WHEN CODIGO_ESCUELA IN (41, 42, 43) THEN 'FACULTAD FARMACIA Y BIOQUIMICA'
		   WHEN CODIGO_ESCUELA IN (51) THEN 'FACULTAD ODONTOLOGIA'
		   WHEN CODIGO_ESCUELA IN (81) THEN 'FACULTAD MEDICINA VETERINARIA'
		   WHEN CODIGO_ESCUELA IN (181, 1814, 182, 1815, 1816) THEN 'FACULTAD PSICOLOGIA'
		   -- CIENCIAS BASICAS
		   WHEN CODIGO_ESCUELA IN (101, 102, 103) THEN 'FACULTAD BIOLOGIA'
		   WHEN CODIGO_ESCUELA IN (131, 132) THEN 'FACULTAD FISICA'
		   WHEN CODIGO_ESCUELA IN (141, 142, 144, 145, 1414, 1424, 1444, 1454) THEN 'FACULTAD MATEMATICA'
		   -- INGENIERIAS
		   WHEN CODIGO_ESCUELA IN (162, 163, 165,  1623, 1653, 166, 167, 168, 169) THEN 'FACULTAD INGENIERIAS GEOLOGICA, MINERA METALURGICA Y GEOGRAFICA'
		   WHEN CODIGO_ESCUELA IN (171, 172, 173) THEN 'FACULTAD INGENIERIA INDUSTRIAL'
		   WHEN CODIGO_ESCUELA IN (191, 192, 1924, 193, 194, 195, 196) THEN 'FACULTAD INGENIERIA ELECTRONICA Y ELECTRICA'
		   WHEN CODIGO_ESCUELA IN (201, 202, 203) THEN 'FACULTAD INGENIERIA SISTEMAS E INFORMATICA'
		   WHEN CODIGO_ESCUELA IN (71, 72, 73, 734, 735, 74) THEN 'FACULTAD DE QUIMICA E INGENIERIA QUIMICA'
		   -- CIENCIAS ECONOMICAS Y DE GESTION
		   WHEN CODIGO_ESCUELA IN (91, 911, 912, 914, 915,92, 921, 922, 93, 931, 932, 94, 95, 957, 96) THEN 'FACULTAD CIENCIAS ADMINISTRATIVAS'
		   WHEN CODIGO_ESCUELA IN (111, 1111, 1112, 1113, 1114, 1115, 112, 1121, 113, 1131, 114, 1141, 115) THEN 'FACULTAD CIENCIAS CONTABLES'
		   WHEN CODIGO_ESCUELA IN (121, 122, 123) THEN 'FACULTAD CIENCIAS ECONOMICAS'
		   -- HUMANIDADEES Y CIENCIAS JURIDICAS Y SOCIALES
		   WHEN CODIGO_ESCUELA IN (31, 310, 33, 34, 35, 36, 37, 38, 39) THEN 'FACULTAD LETRAS Y CIENCIAS HUMANAS'
		   WHEN CODIGO_ESCUELA IN (611, 612, 613, 62, 623) THEN 'FACULTAD EDUCACION'
		   WHEN CODIGO_ESCUELA IN (22, 23, 225) THEN 'FACULTAD DERECHO Y CIENCIAS POLITICA'
		   WHEN CODIGO_ESCUELA IN (151, 152, 153, 154, 155, 157) THEN 'FACULTAD CIENCIAS SOCIALES'
		   END FACULTAD
	FROM Escuelas

)
SELECT *
	,  CASE WHEN FACULTAD IN ('FACULTAD MEDICINA', 'FACULTAD FARMACIA Y BIOQUIMICA', 'FACULTAD ODONTOLOGIA', 'FACULTAD MEDICINA VETERINARIA', 'FACULTAD PSICOLOGIA') THEN 'CIENCIAS DE LA SALUD'
			WHEN FACULTAD IN ('FACULTAD BIOLOGIA', 'FACULTAD FISICA', 'FACULTAD MATEMATICA') THEN 'CIENCIAS BASICAS'
			WHEN FACULTAD IN ('FACULTAD INGENIERIAS GEOLOGICA, MINERA METALURGICA Y GEOGRAFICA', 'FACULTAD INGENIERIA INDUSTRIAL'
							, 'FACULTAD INGENIERIA ELECTRONICA Y ELECTRICA', 'FACULTAD INGENIERIA SISTEMAS E INFORMATICA'
							, 'FACULTAD DE QUIMICA E INGENIERIA QUIMICA') THEN 'INGENIERIAS'
			WHEN FACULTAD IN ('FACULTAD CIENCIAS ADMINISTRATIVAS', 'FACULTAD CIENCIAS CONTABLES',  'FACULTAD CIENCIAS ECONOMICAS') THEN 'CIENCIAS ECONOMICAS Y DE GESTION'
			WHEN FACULTAD IN ('FACULTAD LETRAS Y CIENCIAS HUMANAS', 'FACULTAD EDUCACION', 'FACULTAD DERECHO Y CIENCIAS POLITICA', 'FACULTAD CIENCIAS SOCIALES') THEN 'HUMANIDADES, CIENCIAS JURIDICAS Y SOCIALES'
		    END AREA_ACADEMICA
		INTO #data_admision_facultades
FROM Facultades


/*

SELECT DISTINCT CODIGO_ESCUELA, ESCUELA_PROFESIONAL
FROM #data_admision_facultades
WHERE AREA_ACADEMICA IS NULL

*/

-- REPORTE
-- ===========>

IF OBJECT_ID('Tempdb..#ReportePostulacion','U') IS NOT NULL DROP TABLE #ReportePostulacion     
;WITH reporte1 AS (

		SELECT ANIO
			, TIPO
			, CONCAT(ANIO, '-', TIPO) AS ANIO_TIPO
			, AREA_ACADEMICA
			, FACULTAD
			, CODIGO_ESCUELA
			, ESCUELA_PROFESIONAL_OFICIAL AS ESCUELA_PROFESIONAL
			, COUNT(CODIGO) AS N_POSTULANTES
			, COUNT(CASE WHEN OBS_OFICIAL LIKE '%ALCANZO VACANTE%' THEN CODIGO END) AS N_ALCANZO_VACANTE
			, COUNT(CASE WHEN OBS_OFICIAL IS NULL THEN CODIGO END) AS N_NO_ALCANZO_VACANTE
			, ROUND(AVG(CASE WHEN OBS_OFICIAL LIKE '%ALCANZO VACANTE%' AND PUNTAJE IS NOT NULL THEN PUNTAJE END),2) AS PUNTAJE_PROMEDIO
			, MAX(CASE WHEN OBS_OFICIAL LIKE '%ALCANZO VACANTE%' THEN PUNTAJE END) AS PUNTAJE_MAX
			, MIN(CASE WHEN OBS_OFICIAL LIKE '%ALCANZO VACANTE%' THEN PUNTAJE END) AS PUNTAJE_MIN  
		FROM #data_admision_facultades
		GROUP BY ANIO
			, TIPO
			, CONCAT(ANIO, '-', TIPO)
			, AREA_ACADEMICA
			, FACULTAD
			, CODIGO_ESCUELA
			, ESCUELA_PROFESIONAL_OFICIAL 	
),
reporte2 AS (

	SELECT * 
		, N_POSTULANTES - N_ALCANZO_VACANTE AS DEMANDA
	FROM reporte1

),
reporte3 AS (

	SELECT * 
	    , CASE 
	        WHEN DEMANDA >= 0 AND DEMANDA < 50
				AND ESCUELA_PROFESIONAL NOT LIKE '%S.J.L%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%HUARAL%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%CHILCA%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%CHANCAY%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%HUARMEY%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%OYÓN%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%VILLA RICA%' 
				THEN 1 ELSE 0 
			END AS MENOS_DEMANDA
		  , CASE 
	        WHEN DEMANDA > 500
				AND ESCUELA_PROFESIONAL NOT LIKE '%S.J.L%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%HUARAL%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%CHILCA%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%CHANCAY%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%HUARMEY%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%OYÓN%' 
				AND ESCUELA_PROFESIONAL NOT LIKE '%VILLA RICA%' 
				THEN 1 ELSE 0 
			END AS MAYOR_DEMANDA
	FROM reporte2

										
)
SELECT * 
	, CASE WHEN MAYOR_DEMANDA = 1 OR MENOS_DEMANDA = 1 
			THEN ROUND((CAST(N_ALCANZO_VACANTE AS FLOAT) / CAST(N_POSTULANTES AS FLOAT))*100,2)
			ELSE 0 END PARTICIPACION
	INTO #ReportePostulacion
FROM reporte3;




-- RESUMEN POSTULACION COMPARACION



IF OBJECT_ID('Tempdb..#Escuelas_Fix','U') IS NOT NULL DROP TABLE #Escuelas_Fix
; WITH COD_ESCUELA AS (

	SELECT DISTINCT AREA_ACADEMICA	
		 , FACULTAD
		 , CODIGO_ESCUELA
		 , ESCUELA_PROFESIONAL
	FROM #ReportePostulacion

), NORMALIZAR_ESCUELA AS (

	SELECT *
		, LEFT(CODIGO_ESCUELA, 3) AS CODIGO_ESCUELA_FIX
	    , LEFT(ESCUELA_PROFESIONAL, CHARINDEX(' -', ESCUELA_PROFESIONAL + ' -') - 1) AS ESCUELA_PROFESIONAL_FIX
	FROM COD_ESCUELA

)
SELECT * INTO #Escuelas_Fix
FROM NORMALIZAR_ESCUELA

IF OBJECT_ID('Tempdb..#ReportePostulacionV2','U') IS NOT NULL DROP TABLE #ReportePostulacionV2
SELECT A.*
	 , B.CODIGO_ESCUELA_FIX
	 , B.ESCUELA_PROFESIONAL_FIX
	 INTO #ReportePostulacionV2
FROM #ReportePostulacion AS A
LEFT JOIN #Escuelas_Fix AS B
ON A.CODIGO_ESCUELA = B.CODIGO_ESCUELA
AND A.ESCUELA_PROFESIONAL = B.ESCUELA_PROFESIONAL

-- Construccion Reporte Postulacion
-- ===================================>

TRUNCATE TABLE ReportePostulacion
INSERT INTO ReportePostulacion
SELECT * -- INTO ReportePostulacion
FROM #ReportePostulacionV2


/*

SELECT *
FROM ReportePostulacion

*/







